# Generated by Django 2.2.12 on 2020-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_followers_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('fullname', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
